spring.application.name=3_1_SB_Banking_Transaction_System-practice

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db_Practice_01
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true