spring.application.name=3_2_SB_Wallet_System_Idempotency_Production_Concept

# ===============================
# DATABASE CONFIGURATION
# ===============================


spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=admin
# your PostgreSQL password


# ===============================
# JPA / HIBERNATE CONFIG
# ===============================

spring.jpa.hibernate.ddl-auto=update
# update → automatically creates/updates tables
# (use create-drop only for testing)

spring.jpa.show-sql=true
# shows SQL queries in console (very useful for learning)

spring.jpa.properties.hibernate.format_sql=true
# formats SQL nicely


# ===============================
# POSTGRES DIALECT
# ===============================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# tells Hibernate we are using PostgreSQL


# ===============================
# SQL INITIALIZATION (OPTIONAL)
# ===============================

spring.sql.init.mode=always
# runs data.sql if present


# ===============================
# SERVER PORT (OPTIONAL)
# ===============================

server.port=8080
# default port